# Generated by Django 6.0.2 on 2026-03-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('plex_rating_key', models.CharField(max_length=100, unique=True)),
                ('radarr_id', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('watched', models.BooleanField(default=False)),
                ('file_path', models.TextField(blank=True, default='')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('plex_rating_key', models.CharField(max_length=100, unique=True)),
                ('sonarr_id', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('any_episode_watched', models.BooleanField(default=False)),
                ('total_episodes', models.IntegerField(default=0)),
                ('watched_episodes', models.IntegerField(default=0)),
                ('file_path', models.TextField(blank=True, default='')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['title'],
            },
        ),
    ]
