# Generated by Django 6.0.2 on 2026-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0003_radarr_sonarr_source_of_truth'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
