# Generated by Django 6.0.2 on 2026-03-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0004_add_movie_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
