# Generated by Django 6.0.2 on 2026-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0006_add_deletion_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
