# Generated by Django 6.0.2 on 2026-03-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0007_movie_release_date_series_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
