# Generated by Django 6.0.2 on 2026-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0009_moviecollection_movie_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
